title: HAE Lab
email: sehilyi@gmail.com
description: >-
  HAE Lab
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hae-lab.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sehi_lyi
github_username: hae-lab

styles:
  - /assets/index.css
sass:
  style: compressed

collections:
  areas:
    output: true
  publications:
    output: true
  news:
    output: true
  software:
    output: true
  themes:
    output: true

plugins:
  - jekyll-feed
